spring:
  application:
    name: demo-ws
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp?serverTimeZone=UTC+7
    username: root
    password: password
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
